void main_vertex
(
   float4 color : COLOR,
   uniform float4x4 modelViewProj,
   out float4 oColor : COLOR,
   out float2 oTex : TEXCOORD,
   float2 tex : TEXCOORD,
   out float4 oPosition : POSITION,
   float4 position : POSITION
)
{
   oPosition = mul(modelViewProj, position);
   oTex = tex;
   oColor = color;
}

float4 main_fragment (float2 tex : TEXCOORD, uniform sampler2D s0 : TEXUNIT0) : COLOR
{
   return 0.5 * tex2D(s0, tex);
}

